eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: ms-gestion-abonnements
          uri: lb://MS-GESTION-ABONNEMENTS
          predicates:
            - Path=/abonnements/**
          filters:
            - RewritePath=/abonnements/(?<path>.*), /$\{path}

        - id: ms-gestion-utilisateurs
          uri: lb://MS-GESTION-UTILISATEURS
          predicates:
            - Path=/utilisateurs/**
          filters:
            - RewritePath=/utilisateurs/(?<path>.*), /$\{path}

server:
  port: 6002
