spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MSGestionAbonnements?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "{cipher}b8bcf00226eb5d03bf33f26549865410aad3b8c80b59ffa456fb9e80868b82e8"
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 6006

eureka:
  client:
    registerWithEureka: true # Facultatif
    fetchRegistry: true # Facultatif
    preferIpAddress: true # Facultatif
    serviceUrl:
      defaultZone: http://localhost:6001/eureka